import type { Metadata } from "next";
import { Providers } from "./_providers";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Step-Up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className="bg-gray-200">
        <div className="p-5 bg-gray-600 flex">
          <p className="mr-3 text-white">STEP-UP</p>
          <p>|</p>
          <p className="mx-3 text-white">사원 이름</p>
          <p>|</p>
          <p className="mx-3 cursor-pointer text-white">
            <Link href="/mypage/KimYoungHyeon">나의 현황</Link>
          </p>
          <p>|</p>
          <p className="mx-3 cursor-pointer text-white">
            <Link href="/confirm">결재 현황</Link>
          </p>
          <p>|</p>
          <p className="mx-3 cursor-pointer text-white">
            <Link href="/example">공통 컴포넌트 보러가기</Link>
          </p>
        </div>
        <Providers
          themeProps={{
            attribute: "class",
            // defaultTheme: "system",
            defaultTheme: "light",
            enableSystem: true,
          }}
        >
          <div className="m-10">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
