import type { Metadata } from 'next'
import { Providers } from "./_providers";
import './globals.css'

export const metadata: Metadata = {
  title: 'Step-Up',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <Providers
          themeProps={{
            attribute: "class",
            // defaultTheme: "system",
            defaultTheme: "light",
            enableSystem: true,
          }}
        >
        {children}
        </Providers>
      </body> 
    </html>
  )
}
