import type { Metadata } from "next";
import Header from "../components/Header";
import { layout } from "./confirm";

export const metadata: Metadata = {
  title: "Step-Up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Header />
      <div className={layout()}>{children}</div>
    </div>
  );
}
